### ISSUE TITLE
feature: Add additional "merge" strategy / mode and allow specifying it during init

### ISSUE THREAD

**Issue by thomasmarwitz** [mkdocstrings/griffe-inherited-docstrings#2]
Cf. https://github.com/mkdocstrings/python/issues/194 

Sphinx performs some merging of docstrings[^1], as demonstrated below.
Example:

```python
class Shape:
    contour: list[Point]
    def surface_area(self):
        """Return the surface area in square meters."""
        return numerical_integration(self.contour)
        
class Rectange(Shape)
    def surface_area(self):
		"""Note: This is way faster than the calculation for general shapes!"""
        return distance(self.cotour[2], self.contour[0]) * distance(self.contour[3], self.contour[1])
```
For this example, the merged docstring for `surface_area` should be: "Return the surface area in square meters. Note: This is way faster than the calculation for general shapes!"

Having this feature and being able to set it during init of `InheritDocstringsExtension` would allow to use it in `mkdocs.yml` like this:

```yaml
- mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            extensions:
              - griffe_inherited_docstrings:
                  inherit_docstring_strategy: "merge"
```

Happy to contribute a solution :) 

[^1]: Compare [`MetaLearner.evaluate`](https://metalearners.readthedocs.io/en/latest/api/metalearners.metalearner.html#metalearners.metalearner.MetaLearner.evaluate) with e.g. [`RLearner.evaluate`](https://metalearners.readthedocs.io/en/latest/api/metalearners.rlearner.html#metalearners.rlearner.RLearner.evaluate). Just before `Parameters`, RLearner has an additional paragraph that stems from this [docstring](https://github.com/Quantco/metalearners/blob/a4858da69a9c8b83f2c460fa0240529c75e4f6c2/metalearners/rlearner.py#L359-L362)

**Comment by pawamoy** [comment]
Thanks for opening the issue here again!

So, I'm not convinced by `inherit_docstring_strategy: "merge"`. If we have only two strategies, merge and not merge, we could just have a boolean setting: `merge: true`.

But then... how do we merge? In the previous issue/PR, you also had a delimiter setting IIRC, and had set it to `\n\n` by default. Did that mean parent docstring were truncated at the first delimiter, and then we appended the child docstring? Or did it mean something else?

Could you elaborate your use-case and give examples of parent/child classes? :slightly_smiling_face:

**Comment by thomasmarwitz** [comment]
Yes, I'll elaborate more!

I thought of using `inherit_docstring_strategy: Literal["if_not_present" | "merge"]  = "if_not_present"`. S.t. users don't run another strategy by default after upgrading the package.

You're right, a merge delimiter should also be part of the config, with a default of perhaps `"\n\n"`. A potential issue might be that some docstrings end like this:

```
"""blah
blah""""
```

and others like this:
```
"""blah
blah
""""
```

Having just one `"\n"` as merge delimiter would only lead to the merged child docstring becoming a new paragraph in the second case. Having `"\n\n"` would mitigate that as two empty lines between paragraphs are still rendered as one emtpy line in mkdocs. Merging, as I thought of it would just be `MERGE_DELIMITER.join(docstrings)`.

So the config could look like this:
```yaml
- mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            extensions:
              - griffe_inherited_docstrings:
                  inherit_docstring_strategy: "merge" (default is "if_not_present")
                  merge_delimiter: "\n\n"
```

Example: merge_delimiter = "+", `=>` denotes after merging
```
class Base(Obj):
    "base"    =>    "base"
    ...

class Main(Base):
    "main"    =>    "base+main"
    ...

class Sub(Main):
     "sub"    =>    "base+main+sub"
    ...
```
